trigger:
  branches:
    include:
      - gh-pages

resources:
  repositories:
    - repository: templates
      type: git
      name: 'ENG - Standard/ENG - Standard'
      ref: 'refs/heads/debug/minio'

variables:
  - group: 'mfe-var-group'


stages:
  - stage: Prepare
    jobs:
      - job: Read
        displayName: 'Checkout latest version'
        pool:  'UiPath'

        steps:
          - checkout: self

          # 🔹 Script compatibile con Windows CMD
          - script: |
              for /f %%i in ('type latest') do set LATEST_VERSION=%%i
              echo Latest version is %LATEST_VERSION%
              echo ##vso[task.setvariable variable=latestVersion]%LATEST_VERSION%
              echo ##vso[build.updatebuildnumber]%LATEST_VERSION%
            displayName: 'Read latest version'
            name: printvar

          # 🔹 Upload dell’artifact
          - publish: '$(System.DefaultWorkingDirectory)\$(latestVersion)'
            artifact: latest

  - template: templates/deploy/minio.yml@templates
    parameters:
      dependsOn: 'Prepare'
      environment: 'Minio_Test'
      minioEndpoint: '$(MINIOENDPOINT)'
      minioUsername: '$(MINIOUSER)'
      minioPassword: '$(MINIOPASS)'
      bucket: 'docs'
      deleteBeforeUpload: 'true'
      folder: 'latest'
