site_name: 'Super Project Documentation (EN)'
docs_dir: '../../docs/en'                           # Where to find the markdown files
site_dir: '../../generated/en'                           # Where to put the HTML files

theme:
    name: material
    custom_dir: '../../overrides/'                   # This is where the customization of the theme lives
    logo: assets/images/logo.png                     # The logo is shared by all languages
    favicon: assets/images/favicon.ico               # The favicon is shared by all languages
    language: en                    # The build's language
    features:
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.suggest
extra_css:
  - assets/stylesheets/eng-standard-theme.css                   # CSS is shared by all languages
  - assets/stylesheets/fabric.min.css 
  - assets/stylesheets/toc.css 
  - assets/stylesheets/language-switcher.css                    # Language switcher styles

extra_javascript:
  - assets/js/toc.js  
  - assets/js/language-switcher.js                              # Language switcher functionality

plugins:
  - search:
      lang: en                       # Set language for search
  - render_swagger:
      css: personalization/swagger-ui.css           # Correctly indented plugin config
  - print-site                                      # mkdocs-print-site-plugin

nav:
- Home: index.html
- Developers: developers/index.html
- Administration: Administration/index.html


markdown_extensions:
  - markdown_captions
  - admonition
  - pymdownx.details
  - pymdownx.superfences